# Generated by Django 3.0 on 2019-12-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_login', models.CharField(max_length=255)),
                ('employee_password', models.CharField(max_length=255)),
                ('employee_fio', models.CharField(max_length=255)),
                ('employee_f', models.CharField(max_length=255)),
                ('employee_i', models.CharField(max_length=255)),
                ('employee_o', models.CharField(max_length=255)),
                ('employee_phone_number', models.CharField(max_length=255)),
                ('employee_home_adress', models.CharField(max_length=255)),
                ('employee_voice_example', models.CharField(max_length=255)),
            ],
        ),
    ]
