# Generated by Django 3.0 on 2019-12-20 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securityApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_Status',
            fields=[
                ('call_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('call_status_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Call_Type',
            fields=[
                ('type_call_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_call_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('mode_id', models.AutoField(primary_key=True, serialize=False)),
                ('mode_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_name', models.CharField(max_length=255)),
                ('object_adress', models.CharField(max_length=255)),
                ('object_positions_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('period_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_day', models.CharField(max_length=255)),
                ('plan_time_from', models.TimeField()),
                ('plan_time_to', models.TimeField()),
                ('plan_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='securityApp.Mode')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_phone_number', models.CharField(max_length=255)),
                ('position_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='securityApp.Object')),
            ],
        ),
        migrations.CreateModel(
            name='Status_ChP',
            fields=[
                ('status_chp_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_chp_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type_ChP',
            fields=[
                ('type_chp_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_chp_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tick_ChP',
            fields=[
                ('tick_chp_id', models.AutoField(primary_key=True, serialize=False)),
                ('tick_chp_date', models.DateField()),
                ('tick_chp_time', models.TimeField()),
                ('tick_chp_record_path', models.CharField(max_length=255)),
                ('tick_chp_app_path', models.CharField(max_length=255)),
                ('tick_chp_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='securityApp.Employee')),
                ('tick_chp_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='securityApp.Position')),
                ('tick_chp_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='securityApp.Status_ChP')),
                ('tick_chp_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='securityApp.Type_ChP')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_raw',
            fields=[
                ('plan_raw_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_raw_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='securityApp.Period')),
                ('plan_raw_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='securityApp.Plan')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='securityApp.Position'),
        ),
        migrations.CreateModel(
            name='Close_ChP',
            fields=[
                ('close_chp_id', models.AutoField(primary_key=True, serialize=False)),
                ('close_chp_date', models.DateField()),
                ('close_chp_time', models.TimeField()),
                ('close_chp_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='securityApp.Employee')),
                ('close_chp_is', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='securityApp.Tick_ChP')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('call_date', models.DateField()),
                ('call_time', models.TimeField()),
                ('call_path', models.CharField(max_length=255)),
                ('call_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='securityApp.Employee')),
                ('call_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='securityApp.Position')),
                ('call_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='securityApp.Call_Status')),
                ('call_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='securityApp.Call_Type')),
            ],
        ),
    ]
