# Generated by Django 3.0 on 2020-02-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityApp', '0003_auto_20200211_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_date',
            field=models.DateField(auto_now=True),
        ),
    ]
