# Generated by Django 2.2.7 on 2020-03-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securityApp', '0004_auto_20200211_1321'),
        ('securityApp', '0004_historicalposition'),
    ]

    operations = [
    ]
