# Generated by Django 2.2.7 on 2020-03-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securityApp', '0005_merge_20200302_1224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalPosition',
        ),
    ]
